language: java
jdk: openjdk8

services: mysql
before_install: ./scriptci/travisMariadb.sh

script:  mvn package -DskipTests 

deploy:
  provider: s3
  access_key_id: "$AWS_KEY"
  secret_access_key: "$AWS_SECRET"
  bucket: eschoolbucket
  skip_cleanup: true
  acl: public_read
  local_dir: target
env:
 
  global:
  - secure: eLIqRVPNn6sdnRU6vrN31fq5EkFNymseg2nDhPW8lzp4xydnUtAglXl98gE7+Bbrv1FpLU2F3k4DJ2CfOpr0NxlkXqtWqovNIlShEN6jVP7d5dDcJPfXFsZp0Gr3dO6BlVjEDOigrt/Rl0jCIwq8vYqQ5VXvXFj5186k8oAFb73u6UILOOQUKTvmsuro4hUvxCASXbNp2r5jES1f7ChzN5QA8qT1dMeXDzBQmGOM+vaTdKRS2D/eIjpDZzG+flj008BEm0c6AjkcMtCfa7H87E+PSD6lzrlBP8qEIHOnc0Ct2rj0fag4Pv3B0/rMxtXGe7h6yu6awEdSCBQjjJLJGMR7evRLjtsPf9IMb8d26OXDLgSJwgMni/w3eoFq/YcFhUK0ONkVC4TuXFUzgcSYAB7AHHfYWRrQERxWV38Vcad7ur31sLZSIrQ1rr553SbqN3/nrEutPDT6qIv6vP3N0NrctD7OXd02x8TYCRrU9IRrRGztATidWvVXHv8MDe3Mf4h1d5TRlSEAoYCIwr+Jap2xPDY7gCDbpn+P/UwOyg1oTAc+cm0L+yorfOauioFLF0I9nFL/rwMzLtfjt+Cc4RB+lfFK/8jizSMHSp+5+80eT1Du2EyjlA2FMQDUr24TziM4GsT95p8FL5nR2uNFqqpgJ+Z0OEZOH0YqXZrNKoI=
  - secure: depghlXuN8AqfhCc2I7C3uUTEbOCfquuO/bpWXGrLgLZuWwEN4Z8CEGt2+Deyp6MwmFP8T2pMuV9yWUo3vB4v95Lic6DZ49fUvk8fMWXIGcKLEAL+lwMb83puDbPIMuw0Bw5AlCYu8l5IJG3v5XSZrk0xe541bc0dBwc5ay76g1gM5grTiQrZLH0vwpbzljlhK9SwAYbgUJaGaVKdWrLTpo3Uqabnvzh0B8pxfUgfMqYa0KN4E/ewon31X9gPkFUu2vamtd2Hlolk/OfNjKjr3N121LywH8f4QGOA4x5vkExFggPVP0t4VgyORZM6FLrXkNlsWTZgI8gczzyYaQdrm5k8/D57CUhKOsHm2BBISfLudziRlQ0nTJTjpXiSwWjXIEXpCwfEpE33wFIufrNm954iTbjUtkXs47+hX6L3qvO7vdGcm43ceOdZ0OdS5XLOAsb/vxGty1FFHKIt1BUS8/XfdWcdBYppTJ+zAYPa57LzcxhvVemtdoQTr55Ok26joiSwgT8FraVVMlQ7fdX8BN8Wl/hGRdV9XqzC5fjvxRwyuJkDqLNtYV1pxPcVB4siI4nTCJN1qcG+V7VBwDY2C9L6a4WjOaPy2DIsTaMMI8tgtUcubJp7YpD4uas/nuW/TxMZ0RUd5QauVyyCkWGUyneGdR5CP8uAuUT34sk8M8=
